"""Prompt defaults and helpers."""

from app.prompts.defaults import (
    CLASSIFY_PLACEHOLDERS,
    CLASSIFY_PROMPT,
    CLASSIFY_SYSTEM,
    EXTRACTION_PLACEHOLDERS,
    EXTRACTION_SYSTEM,
    EXTRACTION_USER,
    REPLY_PLACEHOLDERS,
    REPLY_TEMPLATE,
)

__all__ = [
    "CLASSIFY_PLACEHOLDERS",
    "CLASSIFY_PROMPT",
    "CLASSIFY_SYSTEM",
    "EXTRACTION_PLACEHOLDERS",
    "EXTRACTION_SYSTEM",
    "EXTRACTION_USER",
    "REPLY_PLACEHOLDERS",
    "REPLY_TEMPLATE",
]
